export const requestTypes = {
  newRequest: "newRequest",
  cancelRequest: "cancelRequest",
  apiRequest: "apiRequest",
  configRequest: "configRequest",
  layoutConfigRequest: "layoutConfigRequest",
  getHistoryItemRequest: "getHistoryItemRequest",
  getAllHistoryRequest: "getAllHistoryRequest",
  deleteAllHistoryRequest: "deleteAllHistoryRequest",
  deleteHistoryRequest: "deleteHistoryRequest",
  renameHistoryRequest: "renameHistoryRequest",
  openHistoryItemRequest: "openHistoryItemRequest",
  openExistingItemRequest: "openExistingItemRequest",
  getAllCollectionNameRequest: "getAllCollectionNameRequest",
  getAllCollectionsRequest: "getAllCollectionsRequest",
  getCollectionsByIdRequest: "getCollectionsByIdRequest",
  addToCollectionsRequest: "addToCollectionsRequest",
  renameCollectionRequest: "renameCollectionRequest",
  deleteCollectionRequest: "deleteCollectionRequest",
  renameCollectionItemRequest: "renameCollectionItemRequest",
  deleteCollectionItemRequest: "deleteCollectionItemRequest",
  duplicateCollectionsRequest: "duplicateCollectionsRequest",
  saveResponseRequest: "saveResponseRequest",
  saveTestResponseRequest: "saveTestResponseRequest",
  downloadFileTypeRequest: "downloadFileTypeRequest",
  downloadLargeFileRequest: "downloadLargeFileRequest",
  selectFileRequest: "selectFileRequest",
  readFileRequest: "readFileRequest",
  exportRequest: "exportRequest",
  clearRequest: "clearRequest",
  importRequest: "importRequest",
  copyToCollectionsRequest: "copyToCollectionsRequest",
  openVariableItemRequest: "openVariableItemRequest",
  getAllVariableRequest: "getAllVariableRequest",
  getVariableItemRequest: "getVariableItemRequest",
  deleteVariableRequest: "deleteVariableRequest",
  renameVariableRequest: "renameVariableRequest",
  exportVariableRequest: "exportVariableRequest",
  activeVariableRequest: "activeVariableRequest",  
  saveVariableRequest: "saveVariableRequest",
  updateVariableRequest: "updateVariableRequest",
  newVariableRequest: "newVariableRequest",
  attachVariableRequest: "attachVariableRequest",
  removeVariableRequest: "removeVariableRequest",
  getAttchedColIdsRequest: "getAttchedColIdsRequest",
  importVariableRequest: "importVariableRequest",
  duplicateVariableRequest: "duplicateVariableRequest",
  runAllUIOpenRequest: "runAllUIOpenRequest",
  runAllRequest: "runAllRequest",
  openRunRequest: "openRunRequest",
  getRunItemDataRequest: "getRunItemDataRequest",
  exportRunTestJsonRequest: "exportRunTestJsonRequest",
  exportRunTestCSVRequest: "exportRunTestCSVRequest",
  createNewRequest: "createNewRequest"
};

export const responseTypes = {
  apiResponse: "apiResponse",
  cancelResponse: "cancelResponse",
  configResponse: "configResponse",
  layoutConfigResponse: "layoutConfigResponse",
  getHistoryItemResponse: "getHistoryItemResponse",
  getAllHistoryResponse: "getAllHistoryResponse",
  deleteAllHistoryResponse: "deleteAllHistoryResponse",
  deleteHistoryResponse: "deleteHistoryResponse",
  renameHistoryResponse: "renameHistoryResponse",
  openHistoryItemResponse: "openHistoryItemResponse",
  openExistingItemResponse: "openExistingItemResponse",
  newHistoryResponse: "newHistoryResponse",
  getAllCollectionNameResponse: "getAllCollectionNameResponse",
  getAllCollectionNamesResponse: "getAllCollectionNamesResponse",
  getAllCollectionsResponse: "getAllCollectionsResponse",
  getCollectionsByIdResponse: "getCollectionsByIdResponse",
  addToCollectionsResponse: "addToCollectionsResponse",
  appendToCollectionsResponse: "appendToCollectionsResponse",
  duplicateCollectionsResponse: "duplicateCollectionsResponse",
  renameCollectionResponse: "renameCollectionResponse",
  deleteCollectionResponse: "deleteCollectionResponse",
  renameCollectionItemResponse: "renameCollectionItemResponse",
  deleteCollectionItemResponse: "deleteCollectionItemResponse",
  selectFileResponse: "selectFileResponse",
  readFileResponse: "readFileResponse",
  clearResponse: "clearResponse",
  importResponse: "importResponse",
  copyToCollectionsResponse: "copyToCollectionsResponse",
  getAllVariableResponse: "getAllVariableResponse",
  getVariableItemResponse: "getVariableItemResponse",
  deleteVariableResponse: "deleteVariableResponse",
  renameVariableResponse: "renameVariableResponse",
  exportVariableResponse: "exportVariableResponse",
  activeVariableResponse: "activeVariableResponse",
  saveVariableResponse: "saveVariableResponse",
  appendToVariableResponse: "appendToVariableResponse",
  updateVariableResponse: "updateVariableResponse",
  attachVariableResponse: "attachVariableResponse",
  removeVariableResponse: "removeVariableResponse",
  getAttchedColIdsResponse: "getAttchedColIdsResponse",
  importVariableResponse: "importVariableResponse",
  duplicateVariableResponse: "duplicateVariableResponse",
  runAllResponse: "runAllResponse",
  getRunItemDataResponse : "getRunItemDataResponse",
  createNewResponse : "createNewResponse"
};

export function getNonce() {
  let text = '';
  const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  for (let i = 0; i < 32; i++) {
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  }
  return text;
}