export const requestTypes = {
	activeVariableRequest: "activeVariableRequest",
	addToCollectionsRequest: "addToCollectionsRequest",
	apiRequest: "apiRequest",
	attachVariableRequest: "attachVariableRequest",
	bulkExportRequest: "bulkExportRequest",
	bulkColExportRequest: "bulkColExportRequest",
	cancelRequest: "cancelRequest",
	clearRequest: "clearRequest",
	closeItemRequest: "closeItemRequest",
	configRequest: "configRequest",
	convertCurlToJsonRequest: "convertCurlToJsonRequest",
	copyItemRequest: "copyItemRequest",
	copyToCollectionsRequest: "copyToCollectionsRequest",
	createNewFolderRequest: "createNewFolderRequest",
	createNewRequest: "createNewRequest",
	deleteAllCookieRequest: "deleteAllCookieRequest",
	deleteAllHistoryRequest: "deleteAllHistoryRequest",
	deleteCollectionItemRequest: "deleteCollectionItemRequest",
	deleteCollectionRequest: "deleteCollectionRequest",
	deleteCookieByIdRequest: "deleteCookieByIdRequest",
	deleteHistoryRequest: "deleteHistoryRequest",
	deleteVariableRequest: "deleteVariableRequest",
	downloadFileTypeRequest: "downloadFileTypeRequest",
	downloadLargeFileRequest: "downloadLargeFileRequest",
	duplicateCollectionsRequest: "duplicateCollectionsRequest",
	duplicateVariableRequest: "duplicateVariableRequest",
	exportRequest: "exportRequest",
	exportRunTestCSVRequest: "exportRunTestCSVRequest",
	exportRunTestJsonRequest: "exportRunTestJsonRequest",
	exportVariableRequest: "exportVariableRequest",
	formDataFileRequest: "formDataFileRequest",
	getAllCollectionNameRequest: "getAllCollectionNameRequest",
	getAllCollectionsRequest: "getAllCollectionsRequest",
	getAllCookiesRequest: "getAllCookiesRequest",
	getAllHistoryRequest: "getAllHistoryRequest",
	getAllVariableRequest: "getAllVariableRequest",
	getAttachedColIdsRequest: "getAttachedColIdsRequest",
	getCollectionsByIdRequest: "getCollectionsByIdRequest",
	getCollectionsByIdWithPathRequest: "getCollectionsByIdWithPathRequest",
	getColSettingsRequest: "getColSettingsRequest",
	getCookiesByIdRequest: "getCookiesByIdRequest",
	getErrorLogRequest: "getErrorLogRequest",
	getHistoryItemRequest: "getHistoryItemRequest",
	getOpenAndRunItemDataRequest: "getOpenAndRunItemDataRequest",
	getParentSettingsRequest: "getParentSettingsRequest",
	getRunItemDataRequest: "getRunItemDataRequest",
	getVariableItemRequest: "getVariableItemRequest",
	importCurlRequest: "importCurlRequest",
	importRequest: "importRequest",
	importVariableRequest: "importVariableRequest",
	layoutConfigRequest: "layoutConfigRequest",
	multipleApiRequest: "multipleApiRequest",
	newCollectionRequest: "newCollectionRequest",
	newRequest: "newRequest",
	newVariableRequest: "newVariableRequest",
	openAndRunItemRequest: "openAndRunItemRequest",
	openColSettingsRequest: "openColSettingsRequest",
	openExistingItemRequest: "openExistingItemRequest",
	openHistoryItemRequest: "openHistoryItemRequest",
	openManageCookiesRequest: "openManageCookiesRequest",
	openRunRequest: "openRunRequest",
	openSetToVariableUIRequest: "openSetToVariableUIRequest",
	openVariableItemRequest: "openVariableItemRequest",
	pasteItemRequest: "pasteItemRequest",
	readFileRequest: "readFileRequest",
	removeVariableFromColRequest: "removeVariableFromColRequest",
	removeVariableRequest: "removeVariableRequest",
	renameCollectionItemRequest: "renameCollectionItemRequest",
	renameCollectionRequest: "renameCollectionRequest",
	renameHistoryRequest: "renameHistoryRequest",
	renameVariableRequest: "renameVariableRequest",
	runAllRequest: "runAllRequest",
	runAllUIOpenRequest: "runAllUIOpenRequest",
	runCurlRequest: "runCurlRequest",
	saveColSettingsRequest: "saveColSettingsRequest",
	saveCookieRequest: "saveCookieRequest",
	saveRequest: "saveRequest",
	saveResponseRequest: "saveResponseRequest",
	saveTestResponseRequest: "saveTestResponseRequest",
	saveVariableRequest: "saveVariableRequest",
	selectFileRequest: "selectFileRequest",
	selectItemRequest: "selectItemRequest",
	selectPathRequest:"selectPathRequest",
	setToVariableRequest: "setToVariableRequest",
	showMessageRequest:"showMessageRequest",
	themeRequest: "themeRequest",
	tokenRequest: "tokenRequest",
	updateVariableRequest: "updateVariableRequest",
	viewLogRequest: "viewLogRequest"
};

export const responseTypes = {
	activeVariableResponse: "activeVariableResponse",
	addToCollectionsResponse: "addToCollectionsResponse",
	apiResponse: "apiResponse",
	appendToCollectionsResponse: "appendToCollectionsResponse",
	appendToVariableResponse: "appendToVariableResponse",
	attachVariableResponse: "attachVariableResponse",
	bulkColExportResponse: "bulkColExportResponse",
	cancelResponse: "cancelResponse",
	clearResponse: "clearResponse",
	configResponse: "configResponse",
	convertCurlToJsonResponse: "convertCurlToJsonResponse",
	copyItemResponse: "copyItemResponse",
	copyToCollectionsResponse: "copyToCollectionsResponse",
	createNewFolderResponse: "createNewFolderResponse",
	createNewResponse: "createNewResponse",
	curlErrorResponse: "curlErrorResponse",
	deleteAllCookieResponse: "deleteAllCookieResponse",
	deleteAllHistoryResponse: "deleteAllHistoryResponse",
	deleteCollectionItemResponse: "deleteCollectionItemResponse",
	deleteCollectionResponse: "deleteCollectionResponse",
	deleteCookieByIdResponse: "deleteCookieByIdResponse",
	deleteHistoryResponse: "deleteHistoryResponse",
	deleteVariableResponse: "deleteVariableResponse",
	duplicateCollectionsResponse: "duplicateCollectionsResponse",
	duplicateVariableResponse: "duplicateVariableResponse",
	exportVariableResponse: "exportVariableResponse",
	formDataFileResponse: "formDataFileResponse",
	getAllCollectionNameResponse: "getAllCollectionNameResponse",
	getAllCollectionNamesResponse: "getAllCollectionNamesResponse",
	getAllCollectionsResponse: "getAllCollectionsResponse",
	getAllCookiesResponse: "getAllCookiesResponse",
	getAllHistoryResponse: "getAllHistoryResponse",
	getAllVariableResponse: "getAllVariableResponse",
	getAttachedColIdsResponse: "getAttachedColIdsResponse",
	getCollectionsByIdResponse: "getCollectionsByIdResponse",
	getCollectionsByIdWithPathResponse: "getCollectionsByIdWithPathResponse",
	getColSettingsResponse: "getColSettingsResponse",
	getCookiesByIdResponse: "getCookiesByIdResponse",
	getErrorLogResponse: "getErrorLogResponse",
	getHistoryItemResponse: "getHistoryItemResponse",
	getOpenAndRunItemDataResponse: "getOpenAndRunItemDataResponse",
	getParentSettingsResponse: "getParentSettingsResponse",
	getRunItemDataResponse: "getRunItemDataResponse",
	getVariableItemResponse: "getVariableItemResponse",
	importResponse: "importResponse",
	importVariableResponse: "importVariableResponse",
	layoutConfigResponse: "layoutConfigResponse",
	multipleApiResponse: "multipleApiResponse",
	newHistoryResponse: "newHistoryResponse",
	openColSettingsResponse: "openColSettingsResponse",
	openExistingItemResponse: "openExistingItemResponse",
	openHistoryItemResponse: "openHistoryItemResponse",
	pasteItemResponse: "pasteItemResponse",
	readFileResponse: "readFileResponse",
	removeVariableResponse: "removeVariableResponse",
	removeVariableFromColResponse: "removeVariableFromColResponse",
	renameCollectionItemResponse: "renameCollectionItemResponse",
	renameCollectionResponse: "renameCollectionResponse",
	renameHistoryResponse: "renameHistoryResponse",
	renameVariableResponse: "renameVariableResponse",
	runAllResponse: "runAllResponse",
	runCurlResponse: "runCurlResponse",
	saveColSettingsResponse: "saveColSettingsResponse",
	saveCookieResponse: "saveCookieResponse",
	saveResponse: "saveResponse",
	saveVariableResponse: "saveVariableResponse",
	selectFileResponse: "selectFileResponse",
	selectPathResponse: "selectPathResponse",
	setToVariableResponse: "setToVariableResponse",
	tokenResponse: "tokenResponse",
	themeResponse: "themeResponse",
	updateVariableResponse: "updateVariableResponse",
	updateCollectionHistoryItem:"updateCollectionHistoryItem"
};

export const pubSubTypes = {
	addCurrentVariable: "addCurrentVariable",
	updateVariables: "updateVariables",
	removeCurrentVariable: "removeCurrentVariable",
	themeChanged: "themeChanged"
};

export function getNonce() {
	let text = '';
	const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
	for (let i = 0; i < 32; i++) {
		text += possible.charAt(Math.floor(Math.random() * possible.length));
	}
	return text;
}
